version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-prices-app
    container_name: stock-prices-app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

volumes:
  node_modules: